<?php

namespace Al\AlinerieBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsideRepository extends EntityRepository
{
    
    public function get1Zoom(){
	$qb = $this 
	->createQueryBuilder('a')
	->addSelect('a')
	->orderBy('a.date','DESC')
	->andWhere('a.type=1')
	->setMaxResults( 1 );
	return $qb ->getQuery()->getResult();
	}
    
    public function get1Fac(){
	$qb = $this 
	->createQueryBuilder('a')
	->addSelect('a')
	->orderBy('a.date','DESC')
    ->andWhere('a.type=2')
	->setMaxResults( 1 );
	return $qb ->getQuery()->getResult();
	}
}
