<?php

namespace Al\AlinerieBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
     public function getCategories(){
	
	$qb = $this 
	->createQueryBuilder('c')
	->addSelect('c')
	->orderBy('c.id','ASC');
	
	return $qb ->getQuery()->getResult();
	}
    
}
